### ISSUE TITLE
Support for multiple xsd

### ISSUE THREAD

**Issue by Arjun-sna** [reaster/schema-gen#1]
The plugin support configuration of providing the single xsd file. Is there a way to provide a folder which has more than one xsds to be processed?

**Comment by reaster** [comment]
This tool is still pretty green and doesn't support reading multiple schemas, but there is an easy work-around. Create a new xsd file and import your schemas there:
```<?xml version='1.0' encoding='UTF-8'?>
<schema xmlns='http://www.w3.org/2001/XMLSchema'
        elementFormDefault='qualified'
        targetNamespace='http://javagen.com/a'
        xmlns:a='http://javagen.com/a' version='1.0.0'>
    <import namespace='http://javagen.com/a' schemaLocation='./a.xsd' />
    <import namespace='http://javagen.com/b' schemaLocation='./b.xsd' />
</schema>
```
Let me know if this works for you.  I'll include example code in the next update of [schema-gen-examples](https://github.com/reaster/schema-gen-examples).
